services:
  finance-api:
    container_name: finance-api-1
    build:
      context: .
    env_file: .env
    environment:
      - DB_HOST=mysql
      - APP_MODE=api
      - TZ=Asia/Jakarta
      - FIREBASE_PROJECT_ID=finance-go-aead3
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
    volumes:
      - ./secrets/firebase-admin-sdk.json:/app/firebase-credentials.json:ro
      - ./uploads:/app/uploads
    networks:
      - nginx-proxy-manager_default
      - db_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  finance-worker:
    container_name: finance-worker-1
    build:
      context: .
    env_file: .env
    environment:
      - DB_HOST=mysql
      - APP_MODE=worker
      - NOTIFICATION_CRON_SCHEDULE=@every 1m
      - TZ=Asia/Jakarta
      - FIREBASE_PROJECT_ID=finance-go-aead3
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
    volumes:
      - ./secrets/firebase-admin-sdk.json:/app/firebase-credentials.json:ro
    networks:
      - db_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

networks:
  nginx-proxy-manager_default:
    external: true
  db_net:
    external: true
    name: mysql_phpmyadmin_default
