services:
  finance-api:
    container_name: finance-api-1
    build:
      context: .
    env_file: .env
    environment:
      - DB_HOST=mysql
      - APP_MODE=api
      - TZ=Asia/Jakarta
    networks:
      - nginx-proxy-manager_default
      - db_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  finance-worker:
    container_name: finance-worker-1
    build:
      context: .
    env_file: .env
    environment:
      - DB_HOST=mysql
      - APP_MODE=worker
      - NOTIFICATION_CRON_SCHEDULE=@every 1m
      - TZ=Asia/Jakarta
    networks:
      - db_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

networks:
  nginx-proxy-manager_default:
    external: true
  db_net:
    external: true
    name: mysql_phpmyadmin_default
