services:
  finance-app:
    container_name: finance-app-1
    build:
      context: .
    env_file: .env
    environment:
      - DB_HOST=mysql
    networks:
      - nginx-proxy-manager_default
      - db_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

networks:
  nginx-proxy-manager_default:
    external: true
  db_net:
    external: true
    name: mysql_phpmyadmin_default
